### ISSUE TITLE
Siamese loss problem

### ISSUE THREAD

**Issue by SongweiGe** [adambielski/siamese-triplet#18]
Hi when I was using siamese loss as my loss function, I ran into the situation that the derivatives suddenly equaled to nan in some iteration. It turns out that it is because some of the distances equal to 0 (very unlikely to happen) and consequently the derivative sqrt(d) to d is nan. I added a small smooth constant to solve this problem and perhaps you should consider adding a smooth parameter too.

**Comment by adambielski** [comment]
Interesting, thanks for the suggestion. How did you find out this was causing your problem? I suppose it's a very difficult to replicate issue

**Comment by SongweiGe** [comment]
I guess it could happens when there are two exactly the same samples or the parameters of the network contain many 0s. Mine is the former situation.

**Comment by adambielski** [comment]
Added the epsilon - thanks for catching this
