### ISSUE TITLE
AttributeError: 'MNIST' object has no attribute 'train_labels'

### ISSUE THREAD

**Issue by niuqun** [adambielski/siamese-triplet#19]
Dear all,
I ran into this error when I was trying to evaluate the code with SiameseMNIST. It seems that MNIST from PyTorch indeed does not have attributes train_labels or train_data. How do you get these attributes? Could you kindly give some advice? Thank you!

**Comment by adambielski** [comment]
@niuqun They must have changed it in newer version of torchivision; use torchvision 0.1.9 or 0.2.0 and it should work
