### ISSUE TITLE
Have u ever tried soft-margin as in In  paper Defense of the Triplet Loss for Person Re-Identification?

### ISSUE THREAD

**Issue by zhangjinsong3** [adambielski/siamese-triplet#20]
Thanks so much for your amazing work first. And have you tried soft-margin proposed in the person re-id paper? How does it work?

**Comment by adambielski** [comment]
@zhangjinsong3 I have not tried it, I expect it depends on data and domain that you use. I think it should be easy to implement to my code, so you're welcome to try :)
