### ISSUE TITLE
question about FunctionNegativeTripletSelector

### ISSUE THREAD

**Issue by aikudexiaohai** [adambielski/siamese-triplet#21]
i think 
loss_values = ap_distance - distance_matrix[torch.LongTensor(np.array([anchor_positive[0]])), torch.LongTensor(negative_indices)] + self.margin
should be 
loss_values = ap_distance - distance_matrix[torch.LongTensor(np.array([anchor_positive[0]])), torch.LongTensor(negative_indices)]

and in semihard_negative
loss_values < margin, loss_values > 0
should be
loss_values < 0, loss_values > -margin

**Comment by adambielski** [comment]
@aikudexiaohai We need to use the same definition of loss as we use when computing gradients, not sure why you would lose the margin there.

In semihard example, by the definition of the loss it can't be negative. So I don't know what you're suggesting.

There may be many variations of semi-hard negatives, the definition I used here was from the FaceNet paper.
