### ISSUE TITLE
What would you change to feed images into this?

### ISSUE THREAD

**Issue by MotorCityCobra** [adambielski/siamese-triplet#23]
The MNIST set is arrays, (not images).  

When I modify this to take images and return arrays I can't get a good data loader with this repo

    class TripletMNIST(Dataset):

When I'm ready for 'Fit' the cell just shows a [*] forever.  
I try inputing the data loaders as triplet_train_loader.dataset I try to get the array of the image exactly the same size and shape as the MNIST images but I get mismatch errors. I get errors like 1x0x0 "too small". I spent more than a day on the 'too small' problem changing the dims.

BTW, great reop. Beautiful code sewn up very nicely.

**Comment by adambielski** [comment]
Thanks @MotorCityCobra, I hope you solved your problem!
