### ISSUE TITLE
Semi-hard triplet loss implementation

### ISSUE THREAD

**Issue by WrathOfGrapes** [adambielski/siamese-triplet#24]
Excuse me, if I'm wrong, but i believe there is a minor mistake in your semi-hard negative selector:

```
def semihard_negative(loss_values, margin):
    semihard_negatives = np.where(np.logical_and(loss_values < margin, loss_values > 0))[0]
return np.random.choice(semihard_negatives) if len(semihard_negatives) > 0 else None
```
In the FaceNet paper it says that 

> We call these negative exemplars semi-hard , as they are further away from the anchor than the positive exemplar, but still hard because the squared distance is close to the anchorpositive distance. Those negatives lie inside the margin α

Considering that `loss_values` is computed as `ap_distance - distance_matrix[torch.LongTensor(np.array([anchor_positive[0]])), torch.LongTensor(negative_indices)] + self.margin`, you want the |f(x_a) - f(x_p)| - |f(x_a) - f(x_n)| to lie on segment [α, 2α], instead of lying on the interval [-α, \inf].

**Briefly put**: i believe that the function should be defined this way:
```
def semihard_negative(loss_values, margin):
    semihard_negatives = np.where(loss_values > 0)[0]
return np.random.choice(semihard_negatives) if len(semihard_negatives) > 0 else None
```

**Comment by WrathOfGrapes** [comment]
UPD: Found a mistake in my calculations. Actually in your implementation |f(x_a) - f(x_p)| - |f(x_a) - f(x_n)|  lies on a segment [-α,0] (as it does in the paper).

I still don't understand intuition behind this (why we only take negative examples, that are farther away from the anchor than the positive example), but that's a question for FaceNet authors, not you)

**Comment by hamma95** [comment]
> UPD: Found a mistake in my calculations. Actually in your implementation |f(x_a) - f(x_p)| - |f(x_a) - f(x_n)| lies on a segment [-α,0] (as it does in the paper).
> 
> I still don't understand intuition behind this (why we only take negative examples, that are farther away from the anchor than the positive example), but that's a question for FaceNet authors, not you)

the intuition behind that is that negatives that are closer to the anchor than positives make the gradient of the triplets loss null, thusly no weight updates happen.
