### ISSUE TITLE
increase input image size

### ISSUE THREAD

**Issue by attibalazs** [adambielski/siamese-triplet#29]
hi nice work on the repo, thank you for these great examples.

I'm trying to increase the size and getting tensor mismatch errors, cannot really see a way around it. 
Is there a way to not hard code the FC layer input size and get it from the convnet somehow ?

`
RuntimeError: size mismatch, m1: [256 x 179776], m2: [1024 x 256] at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:268`

**Comment by adambielski** [comment]
No, the linear layers need to have their weights initialized so they need to know the input shape. You need to change it accordingly.
To avoid this you could use a network that uses global average pooling after the last spatial output (e.g. after the last convolutional layer), then your input vector has the size of number of channels which doesn't rely on input size. Then you can reshape and apply one last linear layer. You can look at ResNet or Inception networks as an example.

**Comment by Lovebubu** [comment]
Could you give an example for the modification? Thank you.
