### ISSUE TITLE
About choosing hard negative pairs

### ISSUE THREAD

**Issue by cdw1994** [adambielski/siamese-triplet#3]
Maybe in class `HardNegativePairSelector`, the hard negative pairs should be the pairs with closest distances, since the objective is to separate the embeddings in a negative pair. 

If this is not right, just ignore this issue.

**Comment by adambielski** [comment]
@cdw1994 Thanks for spotting this - you're absolutely right, that's a stupid bug. Will fix it now.

**Comment by adambielski** [comment]
Fixed in #4
