### ISSUE TITLE
Extract features from images - Triplet Model

### ISSUE THREAD

**Issue by josianerodrigues** [adambielski/siamese-triplet#34]
Hi @adambielski,

I need to do some testing with the triplet model. My experiments consist of extracting features for each image in the test dataset and using these features for the task of image retrieval. I'm saving the trained model, but I'm not able to load to extract the features of each image because the model is trained for a triplet format input. Some idea?

**Comment by adambielski** [comment]
@josianerodrigues That's what `get_embedding` method in TripletNet is for https://github.com/adambielski/siamese-triplet/blob/master/networks.py#L86
It's also used in the notebook as an example

**Comment by josianerodrigues** [comment]
Thank you :)
