### ISSUE TITLE
ConstrativeLoss implementation

### ISSUE THREAD

**Issue by lspaulucio** [adambielski/siamese-triplet#36]
I think that your ConstrativeLoss implementation could have a problem. 
In the [paper](http://yann.lecun.com/exdb/publis/pdf/hadsell-chopra-lecun-06.pdf) the Constrative Loss is defined by:

![right](https://user-images.githubusercontent.com/17748220/63615565-0df20880-c5bc-11e9-9f8e-81b3e9eaeb4a.jpeg)

But the Constrative Loss function implemented are:

![wrong](https://user-images.githubusercontent.com/17748220/63615566-0df20880-c5bc-11e9-8afd-145d063cef3c.jpeg)

**Comment by adambielski** [comment]
It's exactly the same, with a different definition of labels Y.
