### ISSUE TITLE
the performance of other dataset.

### ISSUE THREAD

**Issue by creat2012** [adambielski/siamese-triplet#37]
in fact, i want know the siamese's performace at cifar10. Do you try it?

**Comment by creat2012** [comment]
i saw you fashionMNIST, i saw not good enough.

**Comment by dvlshah** [comment]
Please address the problem in a more clear manner.

**Comment by adambielski** [comment]
This is just a toy example, relatively shallow network with only a 2D embedding that is easy for visualization. For real use you would definitely use a different network, especially for more complicated datasets.
