### ISSUE TITLE
in network.py why are you set the last layer look like (256,2)?

### ISSUE THREAD

**Issue by samo313** [adambielski/siamese-triplet#42]
would you please describe more about this code?

class EmbeddingNet(nn.Module):
    def __init__(self):
        super(EmbeddingNet, self).__init__()
        self.convnet = nn.Sequential(nn.Conv2d(1, 32, 5), nn.PReLU(),
                                     nn.MaxPool2d(2, stride=2),
                                     nn.Conv2d(32, 64, 5), nn.PReLU(),
                                     nn.MaxPool2d(2, stride=2))

        self.fc = nn.Sequential(nn.Linear(64 * 4 * 4, 256),
                                nn.PReLU(),
                                nn.Linear(256, 256),
                                nn.PReLU(),
                                **nn.Linear(256, 2)**
                                )
I mean the bold line.
we have 10 classes, so, it seems to be 10 instead of 2!!
any help would be appreciated.

**Comment by adambielski** [comment]
This number corresponds to the dimensionality of features, not the number of classes. Contrastive and triplet losses operate directly on these embeddings. It's not a classification network, where the last layer should output scores for each class.
