### ISSUE TITLE
Relu in Triplet loss

### ISSUE THREAD

**Issue by tuandoan998** [adambielski/siamese-triplet#44]
https://github.com/adambielski/siamese-triplet/blob/0c719f9e8f59fa386e8c59d10b2ddde9fac46276/losses.py#L37

Why does you using activate relu here?
Thank you.

**Comment by adambielski** [comment]
ReLU does max(0, x), which is in the definition of triplet loss.

**Comment by tuandoan998** [comment]
oh, I got it. Thank you very much.
