### ISSUE TITLE
Performance of Triplet on huge number of classes ? 

### ISSUE THREAD

**Issue by BerenLuthien** [adambielski/siamese-triplet#48]
Hey, 
Is there any plan to include such complicated dataset as having 10K~100K classes ? 
Intuitionally MNIST is easy because it has only 10 classes for clustering.

Thanks for sharing the great work BTW :)

**Comment by adambielski** [comment]
It can be trained on other datasets, it has been done successfully e.g. for faces (FaceNet reference in readme), the main change is a bigger architecture.

**Comment by BerenLuthien** [comment]
Thanks for response. I knew Facenet was a famous example. 

I meant, do you have any plan to include such a larger dataset with more classes into this project ? Facenet was trained on too huge dataset, though. 
I am looking for some dataset which provides ~10K classes, with ~10 samples per class, that is, about 100K training examples. -- basically something trainable on one GPU.

And I enjoy your Pytorch code, not Google's TF 1.x facenet code :) Besides, Google did not and cannot open source that dataset. 
Thanks

**Comment by adambielski** [comment]
I have no plans to include more datasets, the examples were only to show how the approach can be used and what's the intuition behind it.

**Comment by BerenLuthien** [comment]
QQ: are these embeddings normalized , that is , ||embed||=1 ? Thanks
