### ISSUE TITLE
Different device error 

### ISSUE THREAD

**Issue by heet2201** [adambielski/siamese-triplet#49]
I am initially loading data into CPU and after that passing it to GPU, but it gives the following error,

>  **Input type (torch.cuda.DoubleTensor) and weight type (torch.cuda.FloatTensor) should be the same**

Attaching code at below, (I am using own custom data)

```
class Data_Load(Dataset):
    def __init__(self,train_path,test_path,train):
        # Transforms
        
        # self.transform = transform
        # Read the csv file
        self.train=train
        if self.train:
            self.train_data_info = pd.read_csv(train_path,header=None)
            self.train_data =[] 
            
            print("printing train data length CUHK")
            print(len(self.train_data_info.index))

            for (i,j) in enumerate(np.asarray(self.train_data_info.iloc[:, 0])):
                try:
                    self.train_data.append(np.moveaxis(cv2.imread(j)[:,:,:3]/ 255., -1, 0))
                except:
                    print(j)

            self.train_data = np.stack(self.train_data)
            self.train_labels = np.asarray(self.train_data_info.iloc[:, 1])
            self.train_labels = torch.from_numpy(self.train_labels)

            self.train_data_len = len(self.train_data_info.index)

        else :
            self.test_data_info = pd.read_csv(test_path,header=None)
            self.test_data =[] 

            print("printing test data length CUHK")
            print(len(self.test_data_info.index))

            for (i,j) in enumerate(np.asarray(self.test_data_info.iloc[:, 0])):
                try : 
                    self.test_data.append(np.moveaxis(cv2.imread(j)[:,:,:3] / 255., -1, 0))
                except : 
                    print(j)  

            self.test_data = np.stack(self.test_data)
            self.test_labels = np.asarray(self.test_data_info.iloc[:, 1])
            self.test_labels = torch.from_numpy(self.test_labels)
            
            self.test_data_len = len(self.test_data_info.index)
            

    def __getitem__(self, index):
        if self.train:
            img, target = self.train_data[index], self.train_labels[index]
        else:
            img, target = self.test_data[index], self.test_labels[index]

        return (img,target)

    def __len__(self):
        if self.train :
            return self.train_data_len
        else :
            return `self.test_data_len
```

And in the trainer.py

```
......
for batch_idx, (data, target) in enumerate(train_loader):
        target = target if len(target) > 0 else None
        if not type(data) in (tuple, list):
            data = (data,)
        
        if cuda:
            data = tuple(d.float().cuda() for d in data)
            if target is not None:
                target = target.float().cuda()

        optimizer.zero_grad()
        outputs = model(*data)
.....
```
Traceback :

> ---------------------------------------------------------------------------
> RuntimeError                              Traceback (most recent call last)
> <ipython-input-13-49277b91f203> in <module>()
> ----> 1 fit(online_train_loader, online_test_loader, model, loss_fn, optimizer, scheduler, n_epochs, cuda, log_interval)
> 
> 8 frames
> /content/siamese-triplet/trainer.py in fit(train_loader, val_loader, model, loss_fn, optimizer, scheduler, n_epochs, cuda, log_interval, metrics, start_epoch)
>      21 
>      22         # Train stage
> ---> 23         train_loss, metrics = train_epoch(train_loader, model, loss_fn, optimizer, cuda, log_interval, metrics)
>      24 
>      25         message = 'Epoch: {}/{}. Train set: Average loss: {:.4f}'.format(epoch + 1, n_epochs, train_loss)
> 
> /content/siamese-triplet/trainer.py in train_epoch(train_loader, model, loss_fn, optimizer, cuda, log_interval, metrics)
>      57 
>      58         optimizer.zero_grad()
> ---> 59         outputs = model(*data)
>      60 
>      61         if type(outputs) not in (tuple, list):
> 
> /usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
>     530             result = self._slow_forward(*input, **kwargs)
>     531         else:
> --> 532             result = self.forward(*input, **kwargs)
>     533         for hook in self._forward_hooks.values():
>     534             hook_result = hook(self, input, result)
> 
> /content/siamese-triplet/networks.py in forward(self, x)
>      43 
>      44     def forward(self, x):
> ---> 45         output = self.convnet(x)
>      46         output = output.view(output.size()[0], -1)
>      47         output = self.fc(output)
> 
> /usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
>     530             result = self._slow_forward(*input, **kwargs)
>     531         else:
> --> 532             result = self.forward(*input, **kwargs)
>     533         for hook in self._forward_hooks.values():
>     534             hook_result = hook(self, input, result)
> 
> /usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py in forward(self, input)
>      98     def forward(self, input):
>      99         for module in self:
> --> 100             input = module(input)
>     101         return input
>     102 
> 
> /usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
>     530             result = self._slow_forward(*input, **kwargs)
>     531         else:
> --> 532             result = self.forward(*input, **kwargs)
>     533         for hook in self._forward_hooks.values():
>     534             hook_result = hook(self, input, result)
> 
> /usr/local/lib/python3.6/dist-packages/torch/nn/modules/conv.py in forward(self, input)
>     343 
>     344     def forward(self, input):
> --> 345         return self.conv2d_forward(input, self.weight)
>     346 
>     347 class Conv3d(_ConvNd):
> 
> /usr/local/lib/python3.6/dist-packages/torch/nn/modules/conv.py in conv2d_forward(self, input, weight)
>     340                             _pair(0), self.dilation, self.groups)
>     341         return F.conv2d(input, weight, self.bias, self.stride,
> --> 342                         self.padding, self.dilation, self.groups)
>     343 
>     344     def forward(self, input):
> 
> RuntimeError: Input type (torch.cuda.DoubleTensor) and weight type (torch.cuda.FloatTensor) should be the same

Can anyone help me to sort out? 

Thank You.

**Comment by adambielski** [comment]
It's not different device, it's different data type; convert your data to float (float32)
