### ISSUE TITLE
result of validation set

### ISSUE THREAD

**Issue by XiaoYee** [adambielski/siamese-triplet#6]
The result of validation set is just the last batchsize accuracy of val_loader instead of  the whole,i wonder whether you will fix this for accuracy？

**Comment by adambielski** [comment]
What do you mean? Whenever the `AccumulatedAccuracyMetric` is called, it just adds the number of correctly classified examples and number of all examples, it does not reset every time it's called. The final accuracy is for the entire validation set.

**Comment by XiaoYee** [comment]
yes,it is my fault.Thank you very much！
