### ISSUE TITLE
Avg Nonzero Triplets

### ISSUE THREAD

**Issue by kjwill555** [adambielski/siamese-triplet#9]
Hi, I'm relatively new to the concept of triplet loss and I was just curious about the "Average Nonzero Triplets" metric. What exactly is this measuring? And is this something that should be going down/up/neither during training?

Thanks in advance for the help!

**Comment by adambielski** [comment]
In case of online triplet selection, many triplets are generated per batch. For each triplet a triplet loss function is computed. What the metric does is measure for how many triplets in a batch a condition for triplet loss to be zero is not satisfied (i.e., the distance between an anchor and a positive is greater than the distance between an anchor a negative with margin `m`).
If this value goes down, it means that fewer and fewer triplets violate triplet loss - the network is learning properly

**Comment by huangzhenjie** [comment]
Excuse me. Can this value be less than 1.0? The minimum value I observed during training was 1.0. I read the code, but still can't understand. thanks.
